name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: [ self-hosted, linux, ARM64 ]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_URL }}/kasperry:$GITHUB_RUN_ID
    - name: Tagging master
      run: docker tag ${{ secrets.REGISTRY_URL }}/kasperry:$GITHUB_RUN_ID ${{ secrets.REGISTRY_URL }}/kasperry:latest
    - name: Push latest to docker registry
      run: docker push ${{ secrets.REGISTRY_URL }}/kasperry:latest
    - name: Push GITHUB_RUN_ID to docker registry
      run: docker push ${{ secrets.REGISTRY_URL }}/kasperry:$GITHUB_RUN_ID
    - name: Update kubernetes deployment
      run: helm upgrade --namespace=kasperry kasperry ./helm --set image.repository=${{ secrets.REGISTRY_URL }}/kasperry --set image.tag=$GITHUB_RUN_ID
